In [32]:
import pandas as pd

In [64]:
df = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
df_final = df_test

In [65]:
df_test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [66]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [67]:
# Encode categorical columns
le = LabelEncoder()
for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])
for col in df.select_dtypes(include='object').columns:
    df_test[col] = le.fit_transform(df_test[col])

In [68]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df_test['Age'] = df_test['Age'].fillna(df_test['Age'].median())
df['Fare'] = df['Fare'].fillna(df['Fare'].median())
df_test['Fare'] = df_test['Fare'].fillna(df_test['Fare'].median())
drop_cols = ['Name', 'Ticket', 'Cabin', 'PassengerId']
df = df.drop(columns=[col for col in drop_cols if col in df.columns], errors='ignore')
df_test = df_test.drop(columns=[col for col in drop_cols if col in df_test.columns], errors='ignore')

In [69]:
df_test.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [70]:
# Define X and y
X = df.drop('Survived', axis=1)
y = df['Survived']

In [71]:
# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [72]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [73]:
my_classifier = GradientBoostingClassifier()

In [74]:
my_classifier.fit(X_train, y_train)
preds = my_classifier.predict(X_test)
acc = accuracy_score(y_test, preds)
cm = confusion_matrix(y_test, preds)
print(f"Accuracy: {acc * 100:.2f}%")

Accuracy: 81.01%

In [75]:
# Encode categorical columns
le = LabelEncoder()
for col in df_test.select_dtypes(include='object').columns:
    df_test[col] = le.fit_transform(df_test[col])

In [76]:
df_test.head()

   Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    1  34.5      0      0   7.8292         1
1       3    0  47.0      1      0   7.0000         2
2       2    1  62.0      0      0   9.6875         1
3       3    1  27.0      0      0   8.6625         2
4       3    0  22.0      1      1  12.2875         2

In [77]:
prediction = my_classifier.predict(df_test)

In [79]:
output = pd.DataFrame({
    'PassengerId': df_final['PassengerId'],
    'Survived': prediction
})

In [80]:
output.to_csv('titanic_predictions.csv', index=False)

In [81]:
from google.colab import files
files.download('titanic_predictions.csv')